### ISSUE TITLE
GET Parameters?

### ISSUE THREAD

**Issue by nickyhajal** [Guibi1/sveltekit-api-fetch#1]
Thanks for this library! Finding it really helpful so far.

When I am trying to do a GET request, I don't seem to see where I should attach parameters in a typesafe way.

![CleanShot 2023-08-08 at 19 01 17](https://github.com/Guibi1/sveltekit-api-fetch/assets/1079625/7bfa5e1c-4abe-4a58-9eab-83ab7c71c032)

Any suggestions?

Appreciate it!

**Comment by Guibi1** [comment]
Hi! Thanks for you interest in the project!
Adding type safety for the search params of a request is in my Todo list. For now you can't use the library with search parameters, so the workaround is to use a normal fetch...

I will use this issue to track the progress of that feature.

**Comment by Guibi1** [comment]
This is now a feature in `3.2.0`.
You can declare a `searchParams` z.object in the validation schema and the library will handle the rest!
